### ISSUE TITLE
0 in legend is omitted

### ISSUE THREAD

**Issue by ktetz** [endangeredoxen/fivecentplots#10]
Any 0.0 in the legend is omitted, even if the data is plotted. Issue is reproduced with: 

df = pd.DataFrame(data=dict(x=range(4), y=range(4), z=range(4)))
fcp.plot(df, x='x', y='y', legend='z')

![image](https://user-images.githubusercontent.com/17346741/50995896-b6e06d00-14dd-11e9-9de5-f5071cf9105f.png)

Note that only a numeric 0.0 seems to be affected - if str(0.0) is used things are fine

**Comment by endangeredoxen** [comment]
This was already fixed in a recent commit
