### ISSUE TITLE
stat points omission 

### ISSUE THREAD

**Issue by ktetz** [endangeredoxen/fivecentplots#11]
I'm probably misremembering something, but thought at one point fcp didn't add points for a calculated stat_val - but with latest update it is being rendered: 

a = sp.linspace(0, 10, 10)
m = sp.ones(len(a))
df1 = pd.DataFrame({'x':a, 'm': m, 'lab': 1})
df2 = pd.DataFrame({'x':a, 'm': 2*m, 'lab': 2})
df = pd.concat((df1, df2))
df['y'] = df.x * df.m
fcp.plot(df, x='x', y='y', stat='mean')

![image](https://user-images.githubusercontent.com/17346741/56823518-4f8ec480-6811-11e9-9b50-cd10cd3e8160.png)

Version appears latest:
C:\code\git\fivecentplots>git log
commit d54b8fd98a3fff22882d1729547d1c24c62cce3e
Author: Steve Nicholes <steve.nicholes@gmail.com>
Date:   Mon Jan 14 20:21:01 2019 -0700

**Comment by endangeredoxen** [comment]
fixed in latest commit
