### ISSUE TITLE
issue with adding lines to plot if data is missing

### ISSUE THREAD

**Issue by DeLloyd** [endangeredoxen/fivecentplots#12]
When attempting to plot 'values' vs 'bins' lines cannot be added to the data, only markers. This is believed to be caused by np.nan in every other row of the 'bins' column. 

[Denver_Test_Case.xlsx](https://github.com/endangeredoxen/fivecentplots/files/3143642/Denver_Test_Case.xlsx)

**Comment by endangeredoxen** [comment]
Please add a test case

**Comment by endangeredoxen** [comment]
this is actually a matplotlib issue.  i added a mask of nan values prior to plotting lines so it will work.  should resolve this issue
