### ISSUE TITLE
License Request

### ISSUE THREAD

**Issue by severalfew** [endangeredoxen/fivecentplots#13]
Is this code open to the public domain? Do you have any restrictions on personal/commercial use? I didn't see a license, want to make sure I'm not mis-using.

Full disclosure: It's Stu. Hi!

**Comment by endangeredoxen** [comment]
There is a reference to GPLv3 in the setup.py file.  There are no
restrictions for personal/commercial use under that license framework.  Use
freely and feel free to contribute improvements.

**Comment by endangeredoxen** [comment]
And yes I did recognize it was you.  They only snygard I've ever met!

**Comment by severalfew** [comment]
Thanks! We'll put it to good use. 

Have you ever considered building it as a conda package? We've been doing that with all our scripts/programs.  The dependency chain resolution is really good. We could help contribute a conda recipe if you're interested.

**Comment by endangeredoxen** [comment]
Never looked into that.  I'll look forward to your contribution
