### ISSUE TITLE
overload colors.DEFAULT_COLORS

### ISSUE THREAD

**Issue by ktetz** [endangeredoxen/fivecentplots#17]
Allow users to overload colors.DEFAULT_COLORS to change plot color orders for all plots along with (as part of) setting a theme ... unless there is already a way that I'm missing

Perhaps do this in conjunction with use of Cyclers: 
https://matplotlib.org/3.1.1/tutorials/intermediate/color_cycle.html
https://matplotlib.org/cycler/

**Comment by endangeredoxen** [comment]
Can now add 'colors' key to the theme file with a list of new colors
