### ISSUE TITLE
iter_ticks deprecation

### ISSUE THREAD

**Issue by ktetz** [endangeredoxen/fivecentplots#18]
Warning: 
The iter_ticks function was deprecated in Matplotlib 3.1 and will be removed in 3.3.

Getting the above warning wit any `plot` with Matplotlib 3.1.1 (fcp version 0.3.1)

**Comment by endangeredoxen** [comment]
Fix committed in 0.4.0 version

I copied the iter_ticks function from mpl so the functionality is still present without a warning (since they promise to delete in the future)
