### ISSUE TITLE
setup.py requirements are not in line with actual imports

### ISSUE THREAD

**Issue by FaustinCarter** [endangeredoxen/fivecentplots#19]
At a cursory glance, at least scipy and bokeh are missing. It would be great to be able to install this package in a clean environment and have it properly collect all of its requirements at install.

**Comment by endangeredoxen** [comment]
Agree completely and I was already planning to address this when version
0.4 is released in the next week or so.  Apologies for the inconvenience of
manually installing some packages in the meantime
