### ISSUE TITLE
color percentile in addition to conf_interval

### ISSUE THREAD

**Issue by ktetz** [endangeredoxen/fivecentplots#21]
Would be great to have color fill accept a percentile (np.percentile) and/or a quantile value instead of a confidence interval. 

There are many scenarios where the confidence interval in the mean is quite small but one would like to render a statistic that shows more information about the variance or range - e.g. the 25/75%-tile, 99%, +3sigma, +6sigma, etc. 

https://endangeredoxen.github.io/fivecentplots/0.3.0/plot.html#Confidence-intervals

**Comment by endangeredoxen** [comment]
This has been added but I also realized this (and the conf_int previously) is done on a point-by-point basis so you get a color band around a particular set of y-values at each x-value.  It is not doing a "confidence band" by bootstrap like done in JMP or seaborn.  Will add a ticket to work on that in the future
