### ISSUE TITLE
pd.read_excel xlrd deprecation

### ISSUE THREAD

**Issue by ktetz** [endangeredoxen/fivecentplots#22]
xlrd has deprecated reading .xlsx filetypes (supporting only .xls moving forward). [Pandas 1.2](https://pandas.pydata.org/docs/whatsnew/v1.2.0.html) and later will switch to using _openpyxl_ (which will need to be made a package requirement, likely)  - see [here](https://stackoverflow.com/questions/65254535/xlrd-biffh-xlrderror-excel-xlsx-file-not-supported), [here](https://stackoverflow.com/questions/65250207/pandas-cannot-open-an-excel-xlsx-file)

At present, to be independent of _pandas_ version, can make the following change in keywords.py:

fcp.__version__ == 0.4.1

- kw = pd.read_excel(osjoin(cur_dir, 'keywords.xlsx'), sheet_name=None)
+ kw = pd.read_excel(osjoin(cur_dir, 'keywords.xlsx'), engine='openpyxl', sheet_name=None)

Sorry wasn't looking at the 0.5 branch yet - will check out if this is already addressed. 

Other option would be to re-save keywords.xlsx as keywords.xls.

**Comment by endangeredoxen** [comment]
Thanks for pointing this out.  I think the cleanest route is to include openpxl as a new dependency if this will be the engine of choice for pandas moving forward.  I'll release a patch (0.4.2) and update the next rev as well
