### ISSUE TITLE
overloading of builin `input`

### ISSUE THREAD

**Issue by ktetz** [endangeredoxen/fivecentplots#25]
fcp.__version__== 0.4.0

This line 15 overloads the builtin "input" and then breaks the `set_theme`

> 15> with open(os.path.join(os.path.dirname(__file__), r'version.txt'), 'r') as input:
>     __version__ = input.readlines()[0]

... 
874> entry = input('Entry: ')

fix to use a different variable name such as fid:

> with open(os.path.join(os.path.dirname(__file__), r'version.txt'), 'r') as fid:
>     __version__ = fid.readlines()[0]
>

**Comment by endangeredoxen** [comment]
OK I updated this for future patch release 0.4.2 and next release 0.5.0.  

BTW pip install should put you on v0.4.1 not 0.4.0 → I recommend upgrading

**Comment by ktetz** [comment]
Seems I had cloned and was in the master branch which was is set to 0.4.0:
https://github.com/endangeredoxen/fivecentplots/blob/master/fivecentplots/version.txt

Will stash these changes if you're making them and check out 0.4.2 and/or 0.5.0 (and hopefully make the next issue / fix a PR!)
