### ISSUE TITLE
add datashader support

### ISSUE THREAD

**Issue by endangeredoxen** [endangeredoxen/fivecentplots#35]

**Comment by denver-lloyd** [comment]
A few thoughts on support:

1.) 'Standard' datashader support. i.e. as outlined in the example here: https://datashader.org/
2.) Support for images. I think in this case we would want the user to be able to just pass an image and then within fcp convert the image to row/col locations + data and generate the plot. Perhaps fcp.implot(engine='datashader') could support this?

**Comment by endangeredoxen** [comment]
For (2) are you suggesting we add support to plot directly from an image file (like png) instead of a numpy array or data frame?

**Comment by endangeredoxen** [comment]
Shifting focus to plotly.  If someone wants to pursue this please go for it
