### ISSUE TITLE
Idea: Adding support for Plotly

### ISSUE THREAD

**Issue by P-Kuca** [endangeredoxen/fivecentplots#36]
Hi, 
I love the fact that some of the the JMP capability had been comprehended within the project.
I was wondering if there can be a possibility to extend capability to Plotly (not only Bokeh)? 

Regards
P Kuca

**Comment by endangeredoxen** [comment]
_Were you saying that I would need to create the module for Plotly (like you build for Bokeh)_

Yes this is what I meant.  You (or someone) would need to create a wrapper for plotly similar to engines.mpl or engines.bokeh that maps the api of plotly to what is used in fcp.  Ultimately, how well this works will depend on what is possible natively with plotly itself.  For example, if the boxplot capabilities of plotly are limited (for example, if there are no hooks to add custom grouping labels similar to the JMP variability chart) then you would be out of luck.  Make sense?
