### ISSUE TITLE
grouping columns error on mixed data type

### ISSUE THREAD

**Issue by denver-lloyd** [endangeredoxen/fivecentplots#37]
Sir,

When plotting a dataset that contains a column of mixed type (i.e. int and str) if the column is used as the legend the following error occurs:

![image](https://user-images.githubusercontent.com/49326219/134731684-866745d8-94a5-40c0-97f6-01efe5e1b02d.png)

Example Case:

`import pandas as pd`
`df = pd.DataFrame()`
`df['X'] = [1,2,3,4,5]`
`df['Y'] = df.X**2`
`df['label'] = [1,'2',3,'4',5]`
`fcp.plot(df=df, x='X', y='Y', legend='label')`

Best,
Denver

**Comment by denver-lloyd** [comment]
This is fixed in 5.0 release, nice work.

**Comment by endangeredoxen** [comment]
I think forcing natsort as a dependency is the right thing to do.  Regular
sorted will require a lamba key to work with mixed types and it will give a
different sorting result anyway.  I'll add to 0.5.0 but you can just
install natsort manually in the meantime

**Comment by endangeredoxen** [comment]
natsort by default done in latest push to 0.5.0.  If there is anything else you need to do with this, please reopen
