### ISSUE TITLE
XLRD Error

### ISSUE THREAD

**Issue by jhexner** [endangeredoxen/fivecentplots#45]
After installing I'm getting an XLRDError.
I do not have Excel installed on my system... is this a requirement? Is there any way to bypass this?

Thanks and great package!
Jonathan

XLRDError                                 Traceback (most recent call last)
Input In [108], in <cell line: 1>()
----> 1 import fivecentplots as fcp

File c:\program files\python38\lib\site-packages\fivecentplots\__init__.py:1, in <module>
----> 1 from .fcp import *
      2 from .fcp import __version__

File c:\program files\python38\lib\site-packages\fivecentplots\fcp.py:62, in <module>
     58 sys.path = [osjoin(user_dir, '.fivecentplots')] + sys.path
     60 from defaults import *  # use local file
---> 62 kw = keywords.make_docstrings()
     64 # install requirements for other packages beyond what is in setup.py
     65 INSTALL = {}

File c:\program files\python38\lib\site-packages\fivecentplots\keywords.py:17, in make_docstrings()
     15     kw = pd.read_excel(osjoin(cur_dir, 'keywords.xlsx'), engine='openpyxl', sheet_name=None)
     16 else:
---> 17     kw = pd.read_excel(osjoin(cur_dir, 'keywords.xlsx'), sheet_name=None)
     19 for k, v in kw.items():
     20     kw[k] = kw[k].replace('`', '', regex=True)

File c:\program files\python38\lib\site-packages\pandas\util\_decorators.py:208, in deprecate_kwarg.<locals>._deprecate_kwarg.<locals>.wrapper(*args, **kwargs)
    206     else:
    207         kwargs[new_arg_name] = new_arg_value
--> 208 return func(*args, **kwargs)

File c:\program files\python38\lib\site-packages\pandas\io\excel\_base.py:310, in read_excel(io, sheet_name, header, names, index_col, usecols, squeeze, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, verbose, parse_dates, date_parser, thousands, comment, skip_footer, skipfooter, convert_float, mangle_dupe_cols, **kwds)
    305         raise TypeError(
    306             "read_excel() got an unexpected keyword argument " "`{}`".format(arg)
    307         )
    309 if not isinstance(io, ExcelFile):
--> 310     io = ExcelFile(io, engine=engine)
    311 elif engine and engine != io.engine:
    312     raise ValueError(
    313         "Engine should not be specified when passing "
    314         "an ExcelFile - ExcelFile already has the engine set"
    315     )

File c:\program files\python38\lib\site-packages\pandas\io\excel\_base.py:819, in ExcelFile.__init__(self, io, engine)
    816 # Always a string
    817 self._io = _stringify_path(io)
--> 819 self._reader = self._engines[engine](self._io)

File c:\program files\python38\lib\site-packages\pandas\io\excel\_xlrd.py:21, in _XlrdReader.__init__(self, filepath_or_buffer)
     19 err_msg = "Install xlrd >= 1.0.0 for Excel support"
     20 import_optional_dependency("xlrd", extra=err_msg)
---> 21 super().__init__(filepath_or_buffer)

File c:\program files\python38\lib\site-packages\pandas\io\excel\_base.py:359, in _BaseExcelReader.__init__(self, filepath_or_buffer)
    357     self.book = self.load_workbook(filepath_or_buffer)
    358 elif isinstance(filepath_or_buffer, str):
--> 359     self.book = self.load_workbook(filepath_or_buffer)
    360 else:
    361     raise ValueError(
    362         "Must explicitly set engine if not passing in" " buffer or path for io."
    363     )

File c:\program files\python38\lib\site-packages\pandas\io\excel\_xlrd.py:36, in _XlrdReader.load_workbook(self, filepath_or_buffer)
     34     return open_workbook(file_contents=data)
     35 else:
---> 36     return open_workbook(filepath_or_buffer)

File c:\program files\python38\lib\site-packages\xlrd\__init__.py:170, in open_workbook(filename, logfile, verbosity, use_mmap, file_contents, encoding_override, formatting_info, on_demand, ragged_rows, ignore_workbook_corruption)
    167 # We have to let unknown file formats pass through here, as some ancient
    168 # files that xlrd can parse don't start with the expected signature.
    169 if file_format and file_format != 'xls':
--> 170     raise XLRDError(FILE_FORMAT_DESCRIPTIONS[file_format]+'; not supported')
    172 bk = open_workbook_xls(
    173     filename=filename,
    174     logfile=logfile,
   (...)
    182     ignore_workbook_corruption=ignore_workbook_corruption,
    183 )
    185 return bk

XLRDError: Excel xlsx file; not supported

**Comment by endangeredoxen** [comment]
What version did you try to install?  For v0.4.3 Excel is not a requirement but but either openpxl or xlrd were used to have access to pandas `read_excel` function.  I just tried a clean install of this version on a machine that does not have Excel and was able to import fine.

I removed this altogether in the latest release (still alpha stage) along with many improvements.  I'm inclined to recommend you try that version which should completely bypass the error you had above:  `pip install fivecentplots==0.5.0a2`

**Comment by jhexner** [comment]
Right, I just pulled the latest version from the master and didn't have a problem. It's only with the release version

**Comment by endangeredoxen** [comment]
Ok that's good.  It's strange to me the release version isn't working
though.  I just tried `pip install fivecentplots` in a fresh env and it
worked.  Maybe there is a dependency difference between our systems

**Comment by jhexner** [comment]
Thanks for the quick response, appreciate it.
And kudos on the great framework I really like it!

**Comment by endangeredoxen** [comment]
You bet and thank you for the kind words

**Comment by jhexner** [comment]
Hi,

Is it possible to create a new release? The current release has this XLRD error...
Working of the tag or master is possible but less convenient for deployment.

Thanks
Jonathan

**Comment by endangeredoxen** [comment]
There is already a pre-release you can use for now:  pip install fivecentplots==0.5.0b2

I'll do the full release once the bugs are addressed (hopefully soon)

**Comment by jhexner** [comment]
This doesn't work, since the only version on the global pypi serve is 0.4.3...
 I guess maybe if it's pulled directly off your github page? it's not ideal for deployment...

**Comment by endangeredoxen** [comment]
No, it is pulled directly off of [pypi](https://pypi.org/project/fivecentplots/0.5.0b2/).  You just have to pin the version when you pip install.

I don't know why this wouldn't work for you.  This is exactly how I deploy it now on the multiple systems I manage.  At any rate, I'm still working on the official 0.5.0 release and that may be a few weeks before it is complete
