### ISSUE TITLE
add symlogx and symbology

### ISSUE THREAD

**Issue by endangeredoxen** [endangeredoxen/fivecentplots#53]

**Comment by denver-lloyd** [comment]
It looks like support for this already exists. Did you add it since ticket creation

Either way the axes documentation (fcp.axes()) did not include it, so I added it there.

**Comment by denver-lloyd** [comment]
Added to axes documentation with commit f3afda0.

https://github.com/endangeredoxen/fivecentplots/commit/f3afda08ae0066a9de377adcdbce1a474b288ed0
