### ISSUE TITLE
Issue with pyinstaller

### ISSUE THREAD

**Issue by roeyjiea** [endangeredoxen/fivecentplots#63]
Hi Steve, 

Have you tried bundle the fcp using pyinstaller? The pyinstaller execution was successful, but it show file not found error message. 

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\AppData\\Local\\Temp\\_MEI267962\\fivecentplots\\version.txt'

Thanks.
Regards,
Roey

**Comment by endangeredoxen** [comment]
Never used pyinstaller before.  The error sounds like it is missing some txt files in the src directory that are needed (like version.txt)
