### ISSUE TITLE
boxes/quartiles in violon plots

### ISSUE THREAD

**Issue by ktetz** [endangeredoxen/fivecentplots#8]
Would be nice to have a little line at IQR levels (25%-75%) in violin plots so can just have a violin and still see where a box would go... 

Seaborn goes a little further and has nice little boxes (not necessary) and a few other options:
https://seaborn.pydata.org/generated/seaborn.violinplot.html

**Comment by endangeredoxen** [comment]
Think this will do it:
https://endangeredoxen.github.io/fivecentplots/boxplot.html#Violins
