### ISSUE TITLE
multiple "y" columns as col(s)

### ISSUE THREAD

**Issue by ktetz** [endangeredoxen/fivecentplots#9]
Was trying to have to boxplots as columns and get error: 
   GroupingError: Grouping column "y" is not in the DataFrame

Following the example:
df = pd.read_csv(osjoin(os.path.dirname(fcp.__file__), 'tests', 'fake_data_box.csv'))
# Make a new y column
df['Value*2'] = 2*df['Value']
# This fails: 
fcp.boxplot(df=df, y=['Value', 'Value*2'], groups=['Batch', 'Sample', 'Region'], col='y', ax_size=[300, 300])

These both work:
fcp.boxplot(df=df, y=['Value', 'Value*2'], groups=['Batch', 'Sample', 'Region'], wrap='y', ax_size=[300, 300])
fcp.boxplot(df=df, y=['Value', 'Value*2'], groups=['Batch', 'Sample', 'Region'], row='y', ax_size=[300, 300])

**Comment by endangeredoxen** [comment]
This was by design.  col only works with 'x' and row only works with 'y'
while wrap works with both.  I can look into supporting all options.
